### ISSUE TITLE
Pretty products help

### ISSUE THREAD

**Issue by SophieBellehumeur** [SophieBellehumeur/pretty-products#1]
@wendywarren @karenmendozagarza
For this week's Pretty Products assignment, I had my grids side by side but now they are all in a column and I'm not sure why. Also the favourite icon doesn't seem to be showing up. Lastly, I'm not sure how to have the purple background behind the cart, I made a class for the list item but it seems to only effect the Add to Cart.
Sophia.

**Comment by SophieBellehumeur** [comment]
I managed to get the cart and favourite to show. Although I'm having trouble aligning them.

**Comment by KarenMendozaGarza** [comment]
Hi Sophia, 

I think I found the issue with your cards. In line 13, there's a double colon in your code that may be preventing your grid from working.
https://github.com/SophieBellehumeur/pretty-products/blob/23a1c6cfce3f4c79f96d38be9717077ef91f4b69/css/main.css#L11-L19
You also have `display: flex ` further down, which would override the grid and turn it into a single column flex item. Once you remove both those things, it should fix your two-column grid. 

For your list of icons, make sure you add a `padding-left: 0;` to the `ul` because CSS always adds a default padding of 40px to allow space for the default bullets. The alignment issue lies in the `a` tag holding the cart icon and text. You'll need to set `display: flex` to those as well and center them first, and then the other icons should line up after that because the rest of your code is set up properly.

**Comment by SophieBellehumeur** [comment]
@KarenMendozaGarza @wendywarren
Hi Karen,

I removed the extra colon and the display:flex but the boxes are still in the first column. The centering of the links worked well, but the paragraph and the h1 got pushed out of the box on each one except for the crystal.

Thank you for the help!

**Comment by SophieBellehumeur** [comment]
It was a problem with the links. Everything is working but Markbot is telling me that I need 12% different from the screenshot but it is 13%. It is also saying some links have duplicate content without unique labels, I thought it had to do with the Aria labels but I added them so I'm not sure.
